server:
  port: 8080

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "C:\\Users\\User\\IdeaProjects\\habr-keycloak-apigateway\\src\\main\\resources"

