spring:
  application:
    name: resource-server
  profiles:
    active: dev
  config:
    import: 'spring.config.import=optional:configserver:http:localhost:38071' #optional:configserver:http://localhost:38071