server:
  port: 8080

logging:
  level:
    root: info
#  pattern:
#    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

spring:
  application.name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      #      default-filters: TokenRelay=
      routes:
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: panda-service
          uri: lb://panda-service
          predicates:
            - Path=/api/panda/**

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:28080/realms/i113_realm
#        registration:
#          keycloak:
#            provider: keycloak
#            scope: openid
#            client-id: 113_gateway_client
#            client-secret: 7SbiE7sVoKL08D1ZJPtSuzSHL7EIJnic
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    statusPageUrlPath: actuator/info
    healthCheckUrlPath: actuator/health
    instance-id: "${spring.application.name}:${random.uuid}" #возможность поднимать несколько микрух. запросы будут идти поочерёдно на каждый

