server:
  port: 8080
  ip: localhost

logging:
  level:
    root: info

spring:
  application.name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: eureka-server
          uri: http://${server.ip}:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: eureka-server-static
          uri: http://${server.ip}:8761
          predicates:
            - Path=/eureka/**

        - id: api-panda-service
          uri: lb://api-panda-service
          predicates:
            - Path=/api/panda/**

        - id: api-events-service
          uri: lb://api-events-service
          predicates:
            - Path=/api/events/**

        - id: api-resource-service
          uri: lb://api-resource-service
          predicates:
            - Path=/api/resource/**

        - id: api-telbot-service
          uri: lb://api-telbot-service
          predicates:
            - Path=/api/telbot/**

#          filters:
#            TokenRelay=

#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: keycloak-provider
#            client-id: i113_gateway_client
#            client-secret: 7SbiE7sVoKL08D1ZJPtSuzSHL7EIJnic
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
#            scope:
#              - openid
#              - message.read
#        provider:
#          keycloak-provider:
#            issuer-uri: http://localhost:28080/realms/i113_realm

eureka:
  client:
    service-url:
      defaultZone: http://${server.ip}:8761/eureka

  instance:
    statusPageUrlPath: actuator/info
    healthCheckUrlPath: actuator/health
    instance-id: "${spring.application.name}:${random.uuid}" #возможность поднимать несколько микрух. запросы будут идти поочерёдно на каждый
