server:
  port: 8081

#Logging
logging:
  level:
    root: info
  file:
    name: logs/resources/resources.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=resources
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  properties:
    hibernate:
      default_schema: resources
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgrespw
    default-schema: resources

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


