name: Cerg-action-process
on: 
  push:
    branches: 
      -master

jobs:
  validating_docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkUser
        run : echo "Hello Message"

    
