name: Cerg-action-process
on: 
  push:
    branches: 
      - master

jobs:
  validating_docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkUser
        run : echo $USER
      - name: Docker version
        run : docker version
      - name: Docker ps
        run : docker ps        

    
