name: cerg-action-process
env:
  APPLICATION_NAME : "CERJ"
on: 
  push:
    branches: 
      - master

jobs:
  CerjDocker:
    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name: ${{ env.APPLICATION_NAME}}"
          
      - name: Checkout
        uses: actions/checkout@v1     

      - name: Maven Eureca clean-build
        run : |
          cd i113_eureka
          mvn clean
          mvn install
          cd -
          
      - name: Docker Eureca update
        run : |
          pwd
          cd i113_eureka
          ./i113_gateway_update.sh
          cd -         
          
      - name: Maven Gateway clean-build
        run : |
          cd i113_gateway
          mvn clean
          mvn install
          cd - 
          
      - name: Docker Gateway update
        run : |
          cd i113_eureka
          ./i113_gateway_update.sh
          cd -           

      - name: Maven Resources clean-build
        run : |
          cd i113_resources
          mvn clean
          mvn install
          cd -  
          
      - name: Docker Resources update
        run : |
          cd i113_eureka
          ./i113_resources_update.sh    
          cd -           
                 
        


