name: cerg-action-process
env:
  APPLICATION_NAME : "CERJ"
on: 
  push:
    branches: 
      - master

jobs:
  validating_docker:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        run : |
          echo "Acclication name: ${{ env.APPLICATION_NAME }}"
          echo pwd


